CC = cc
CUNIT_FLAGS = -lcunit
OBJS =  point.o edge.o triangle.o circle.o listnode.o list.o geom_test.o

test: $(OBJS)
	$(CC) $(OBJS) $(CUNIT_FLAGS) -g -o geom_test

$(OBJS):
 
clean:
	rm *.o geom_test
